# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRecruitment():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_recruitment(self):
    self.driver.get("http://localhost/OrangeHRM/web/index.php/auth/login")
    self.driver.set_window_size(974, 528)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(5) .oxd-text").click()
    self.driver.find_element(By.LINK_TEXT, "Vacancies").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys("soft eng")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text-input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-topbar-body-nav-tab:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-topbar-body-nav-tab:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(2) .\\--left").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(2) .oxd-icon-button:nth-child(2) > .oxd-icon").click()
    self.vars["win795"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win795"])
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-card-container:nth-child(1) .oxd-button").click()
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("Debopom")
    self.driver.find_element(By.NAME, "lastName").send_keys("Sutradhar")
    self.driver.find_element(By.NAME, "email").send_keys("dsutradhar201046@bscse.uiu.ac.bd")
    self.driver.find_element(By.NAME, "contactNumber").send_keys("01745349896")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-file-button").click()
    self.driver.find_element(By.NAME, "resume").send_keys("C:\\fakepath\\Project Proposal_Group 3.pdf")
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-applicant-container-grid-checkbox .oxd-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-check").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--text").click()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.LINK_TEXT, "Vacancies").click()
    self.driver.find_element(By.LINK_TEXT, "Candidates").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-eye-fill").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    self.driver.execute_script("window.scrollTo(0,295)")
    self.driver.find_element(By.LINK_TEXT, "Candidates").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-header-slot-content .data").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-cell:nth-child(4) .header").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--visited").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--toggle > .oxd-icon-button").click()
  
