# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLeavetest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_leavetest(self):
    self.driver.get("http://localhost/OrangeHRM/web/index.php/auth/login")
    self.driver.set_window_size(974, 528)
    self.driver.find_element(By.NAME, "username").send_keys("kshawpnil")
    self.driver.find_element(By.NAME, "password").send_keys("12345678Ab@12345678")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("admin@admin.com")
    self.driver.find_element(By.NAME, "password").send_keys("SQA@admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(3) .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-topbar-body-nav-tab:nth-child(3) > .oxd-topbar-body-nav-tab-item").click()
    self.driver.find_element(By.LINK_TEXT, "Add Entitlements").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").send_keys("Kazi  Shawpnil")
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(3) .oxd-grid-item:nth-child(1) .oxd-input-group__label-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.NAME, "username").send_keys("admin@admin.com")
    self.driver.find_element(By.NAME, "password").send_keys("SQA@admin123")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("mzeba@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("MZeba1234@")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.LINK_TEXT, "Leave").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text-input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) .oxd-input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.NAME, "username").send_keys("mzeba@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("MZeba1234@")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("admin@admin.com")
    self.driver.find_element(By.NAME, "password").send_keys("SQA@admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(3) .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--label-success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-userdropdown-tab").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.NAME, "username").send_keys("admin@admin.com")
    self.driver.find_element(By.NAME, "password").send_keys("SQA@admin123")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("mzeba@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("MZeba1234@")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(1) .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-dropdown:nth-child(2) > .oxd-icon-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-dropdown:nth-child(2) > .oxd-icon-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-dropdown-item:nth-child(2)").click()
  
