# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPIM():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pIM(self):
    self.driver.get("http://localhost/OrangeHRM/web/index.php/auth/login")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.NAME, "username").send_keys("mzeba@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("MZeba1234@")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.close()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/aside/nav/div[2]/ul/li[2]/a/span").click()
  
